# Build the read-only report workbook (Phase 10): macro-free xlsx derived from
# the frozen macro-free base with fixture rows cleared (clean state, matching
# the production workbook), plus an explicit READ-ONLY banner. No VBA, no
# write path into the master.
$ErrorActionPreference = "Continue"
$Root = "C:\Users\Q\Documents\laboratory-inventory-excel"
$Src = "$Root\workbook\LabInventory_v0.1.xlsx"
$Dst = "$Root\workbook\LabInventory_v1.0.0-readonly-report.xlsx"
$LogFile = "$Root\evidence\vba\build-readonly-log.txt"
$lines = New-Object System.Collections.Generic.List[string]
$excel = $null
try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $true
    $excel.DisplayAlerts = $false
    $wb = $excel.Workbooks.Open($Src, 0, $false)
    $lines.Add("opened macro-free base")

    # clear fixture rows from operational tables (same as production build)
    foreach ($tn in @("tblProducts", "tblContainers", "tblTransactions", "tblSuppliers", "tblLocations")) {
        foreach ($wsObj in @($wb.Worksheets)) {
            $lo = $null
            try { $lo = $wsObj.ListObjects.Item($tn) } catch { $lo = $null }
            if ($null -ne $lo) {
                $wsObj.Unprotect()
                while ($lo.DataBodyRange -ne $null -and $lo.DataBodyRange.Rows.Count -gt 0) {
                    $lo.ListRows.Item(1).Delete()
                }
                $wsObj.Protect()
                $lines.Add("cleared " + $tn)
                break
            }
        }
    }

    # READ-ONLY banner on Dashboard
    $dash = $wb.Worksheets.Item("Dashboard")
    $dash.Unprotect()
    $dash.Cells.Item(1, 1).Value2 = "READ-ONLY REPORT - macro-free snapshot. Regenerated by the writer PC. Do not edit."
    $dash.Protect()

    $wb.SaveAs($Dst, 51)
    $lines.Add("saved read-only report")
    $wb.Close($false)
} catch {
    $lines.Add("ERR: " + $_.Exception.Message)
} finally {
    if ($excel) { try { $excel.Quit() } catch {}; try { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null } catch {} }
    [System.IO.File]::WriteAllLines($LogFile, $lines)
    Write-Output ($lines -join "`n")
}
